### ISSUE TITLE
upgrade to guzzle v7+

### ISSUE THREAD

**Issue by nekromoff** [xmhafiz/fb-page-feed#19]
when guzzle v7+ is in composer
```
- xmhafiz/fb-page-feed 1.1.4 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for xmhafiz/fb-page-feed ^1.1.4 -> satisfiable by xmhafiz/fb-page-feed[1.1.4].
```

**Comment by xmhafiz** [comment]
Sorry for late response. Thanks for your feedback 👍🏼
This issue should be solved in #15 as we changed to Zttp. Please check in latest version 1.1.5.

**Comment by glupeksha** [comment]
I have the same issue

`  Problem 1
    - kitetail/zttp v0.6.0 requires guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.5] but it conflicts with your root composer.json require (^7.0.1).
    - xmhafiz/fb-page-feed 1.1.5 requires kitetail/zttp ^0.6.0 -> satisfiable by kitetail/zttp[v0.6.0].
    - Root composer.json requires xmhafiz/fb-page-feed ^1.1.5 -> satisfiable by xmhafiz/fb-page-feed[1.1.5].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.`

**Comment by xmhafiz** [comment]
> I have the same issue with 1.1.5
> 
> ```
> Problem 1
>    - kitetail/zttp v0.6.0 requires guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.5] but it conflicts with your root composer.json require (^7.0.1).
>    - xmhafiz/fb-page-feed 1.1.5 requires kitetail/zttp ^0.6.0 -> satisfiable by kitetail/zttp[v0.6.0].
>    - Root composer.json requires xmhafiz/fb-page-feed ^1.1.5 -> satisfiable by xmhafiz/fb-page-feed[1.1.5].
> ```

@glupeksha Thanks for the report. I will make a fix and get back to you soon. Probably we will change back from zttp to guzzle with latest version.
