### ISSUE TITLE
"An access token is required to request this resource." 

### ISSUE THREAD

**Issue by huubl** [xmhafiz/fb-page-feed#20]
Hi,

Should the API request work without manually setting an access token?

```
$config = [
  'secret_key' => '0101010101',
  'app_id' => '0101010101',
  'page_name' => 'mypage'
  'access_token' => '',
];
$data = FbFeed::make($config)->fetch();
var_dump($data);
```

Because, when leaving the access token empty(or commented out) I get:

`"An access token is required to request this resource." `

I think something goes wrong [here](https://github.com/xmhafiz/fb-page-feed/blob/master/src/FbFeed.php#L223), this returns `false` instead of the merged `app_id` with `secret_key`.

**Comment by xmhafiz** [comment]
You are right, `access_token` field is required. We will update update the readme accordingly. Thanks @huubl

**Comment by SimonEast** [comment]
I don't think the README got updated. It seems to still show a blank `access_token`.
