### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function fb_feed()

### ISSUE THREAD

**Issue by osimer** [xmhafiz/fb-page-feed#3]
Hi there, I did everything as it was in tutorial, but it does not work at all :/. For more information, see my screenshot or https://beta.runwaycamp.cz/assets/test.php .
![snimek z 2018-02-10 23-01-04](https://user-images.githubusercontent.com/26204580/36067095-7d072282-0eb6-11e8-968e-c4f47ad29a03.png)

**Comment by xmhafiz** [comment]
Hi Osimer, 

Thanks for your feedback. I have updated package version. Now, the composer will retrieve version ^1.1 instead of ^1.0. This should resolve the error. Also please change the fbAppId and fbSecretKey according to Step 1

**Comment by xmhafiz** [comment]
You may change the version in composer.json as below.

`{
    "require": {
        "xmhafiz/fb-page-feed": "^1.1"
    }
}`

**Comment by osimer** [comment]
Thanks, it solved the problem!
