### ISSUE TITLE
Endpoint must be reviewed and approved

### ISSUE THREAD

**Issue by ayoub-bousetta** [xmhafiz/fb-page-feed#6]
Hello 
Im getting the following msg: To use 'Page Public Content Access', your use of this endpoint must be reviewed and approved.

i guess it will never work if your app isn't reviewed and approved by facebook, is that true ?

is there any kind of solution to bypass this issue.

Thank you for sharing

**Comment by xmhafiz** [comment]
@ayoub-bousetta thanks for your feedback.

Yes, this is related to the review process as stated in [Feature Review](https://developers.facebook.com/docs/apps/review/feature#reference-PAGES_ACCESS) page. Currently, I suppose there isn't solution to skip the process.

**Comment by SimonEast** [comment]
For anyone else stumbling across this thread, there are a couple of ways to access a page's posts through the API. *One* of the ways requires the "Page Public Content Access" permission/feature, which is probably what this PHP library uses. 

However, if you can get one of the Page's Admins to generate a "Page Access Token" then you can use that and don't need to go through the manual review process.

Unfortunately the Page Access Tokens expire every 1-2 hours by default. You can go through a process to extend them up to 3 months, but I think they still expire after that. There's probably some code that allows you to request a fresh token, but I haven't figured that part out yet.

It would be good if this library supported that method too. Maybe it does if you supply the right token? I haven't yet tested.
