### ISSUE TITLE
Add setLocale

### ISSUE THREAD

**Issue by fiote** [xmhafiz/fb-page-feed#8]
I post in multiple idioms on my page so I need to be able to select the language when requesting the feed. I updated my version of your package locally but it would be nice if you could add it to the base code. Here are the changes :)

line 17
`    private $locale = null;`

line 80
```
    /**
     * @param $locale
     * @return $this
     */
    function setLocale($locale) {
        $this->locale = $locale;
        return $this;
    }
```

line 142
```
            if ($this->locale) {
                $query['query']['locale'] = $this->locale;
            }
```

**Comment by xmhafiz** [comment]
great, please create a pull request

**Comment by afiqiqmal** [comment]
#10 Pull Request
