### ISSUE TITLE
 Call to undefined method Xmhafiz\FbFeed\FbFeed::setAccessToken() 

### ISSUE THREAD

**Issue by emerika** [xmhafiz/fb-page-feed#9]
This is from the example:

$data = fb_feed()
    ->setAccessToken($accessToken)
    ->setPage($fbPageName)
    ->fetch();

However, I can't find the function in the code

**Comment by xmhafiz** [comment]
Thanks for the feedback @emerika. I have updated the version in packagist and it should solve the issue.

You can simply run this command `composer require xmhafiz/fb-page-feed:1.1.3` to update to latest version which include the `setAccessToken` feature.
